### ISSUE TITLE
[Question] How could we insertOrUpdate an Object? (an image for example)

### ISSUE THREAD

**Issue by XabierGoros** [GoogleCloudPlatform/csharp-docs-samples#21]
How could we insertOrUpdate an Object? Do we have to check if it exists, and if so [delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete) and upload it again? I'm using image storing and in my tests [insert](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) does not update or override the image with the same name.

**Comment by remi** [comment]
What does your insert code look like?

Inserting an object for a name should replace the previous object with the same name AFAIK

Here's a sample that:
 - Verifies that an object does not exist yet
 - Inserts object and verifies content was inserted
 - Inserts object with changed content and verifies changed content was inserted
 - Cleans up by deleting the object

```cs
using System;
using System.IO;
using System.Net;
using System.Text;

using Google.Apis.Services;
using Google.Apis.Storage.v1;
using Google.Apis.Auth.OAuth2;

var credentials = GoogleCredential.GetApplicationDefaultAsync().Result;
var storage = new StorageService(new BaseClientService.Initializer() {
    HttpClientInitializer = credentials
});

var bucketName = "YOUR-BUCKET-NAME";

/*
 * Does my-object.txt exist?
 */
try {
    var initialObject = storage.Objects.Get(bucketName, "myObject.txt").Execute();
    Console.WriteLine($"my-object.txt exists ({initialObject.Name}) ({initialObject.ContentType})");
} catch (Google.GoogleApiException ex) {
    if (ex.HttpStatusCode == HttpStatusCode.NotFound)
        Console.WriteLine($"my-object.txt not found");
    else
        throw;
}

/*
 * Insert my-object.txt
 */
storage.Objects.Insert(
    bucket:      bucketName,
    contentType: "text/plain",
    body:        new Google.Apis.Storage.v1.Data.Object() { Name = "myObject.txt" },
    stream:      new MemoryStream(Encoding.UTF8.GetBytes("I am a GCS object!"))
).Upload();

var myObject = storage.Objects.Get(bucketName, "myObject.txt").Execute();
Console.WriteLine($"my-object.txt uploaded ({myObject.Name}) ({myObject.ContentType})");

using (var stream = new MemoryStream()) {
    storage.Objects.Get(bucketName, "myObject.txt").Download(stream);
    Console.WriteLine($"my-object.txt content: {Encoding.UTF8.GetString(stream.GetBuffer())}");
}

/*
 * Insert my-object.txt again, this time with different content
 */
storage.Objects.Insert(
    bucket:      bucketName,
    contentType: "text/plain",
    body:        new Google.Apis.Storage.v1.Data.Object() { Name = "myObject.txt" },
    stream:      new MemoryStream(Encoding.UTF8.GetBytes("I am a GCS object with CHANGED content!"))
).Upload();

var updatedObject = storage.Objects.Get(bucketName, "myObject.txt").Execute();
Console.WriteLine($"updated my-object.txt ({updatedObject.Name}) ({updatedObject.ContentType})");

using (var stream = new MemoryStream()) {
    storage.Objects.Get(bucketName, "myObject.txt").Download(stream);
    Console.WriteLine($"updated my-object.txt content: {Encoding.UTF8.GetString(stream.GetBuffer())}");
}

/* Clean up */
storage.Objects.Delete(bucketName, "myObject.txt").Execute();
```

When I run the sample, I get the following output:

```
my-object.txt not found
my-object.txt uploaded (myObject.txt) (text/plain)
my-object.txt content: I am a GCS object!                                                                                                                                                                                                       
updated my-object.txt (myObject.txt) (text/plain)
updated my-object.txt content: I am a GCS object with CHANGED content!
```

**Comment by XabierGoros** [comment]
Thanks for answering remi.

Wow! This is what I've discovered with my picture uploading use case:

_Pre: My bucket has the Image1_
1. Upload Image2
2. Open it in a browser without cache -> shows Image1

_Pre: My bucket has the Image1_
1. Upload Image2
2. Download Image2 and compute it's hash -> it matches with the Image2 one
3. Open it in a browser without cache -> shows Image2!

So, it seems it is mandatory to download a resource after uploading it?

**Comment by remi** [comment]
If you upload an image and then visit it in your browser, your browser will cache it.

To change the default HTTP caching headers for a Cloud Storage object, see: [Working With Object Metadata > Cache-control](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#cache-control)

By default, I believe the image will be served to the browser with `Cache-control: public,max-age=3600`
